// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/mDir copy.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElectronVersions: typeof import('./src/components/ElectronVersions.vue')['default']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElMenuMenu: typeof import('element-plus/es')['ElMenuMenu']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Home: typeof import('./src/components/Home.vue')['default']
    MDir: typeof import('./src/components/mDir.vue')['default']
    MFile: typeof import('./src/components/mFile.vue')['default']
    Mtree: typeof import('./src/components/tree/mtree.vue')['default']
    MTree: typeof import('./src/components/mTree.vue')['default']
    ReactiveCounter: typeof import('./src/components/ReactiveCounter.vue')['default']
    ReactiveHash: typeof import('./src/components/ReactiveHash.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tree: typeof import('./src/components/tree/tree.vue')['default']
    TreeC: typeof import('./src/components/tree/TreeC.vue')['default']
  }
}
